-- =============================================================
-- CALCULATE GPA PLUS - SUPABASE FREE DATABASE SCHEMA SCRIPT
-- Paste this script into your Supabase SQL Editor and click "Run"
-- =============================================================

-- 1. Profiles Table
CREATE TABLE IF NOT EXISTS public.profiles (
  id TEXT PRIMARY KEY,
  profile_name TEXT NOT NULL,
  university TEXT NOT NULL,
  faculty TEXT NOT NULL,
  degree TEXT NOT NULL,
  academic_year TEXT DEFAULT '',
  description TEXT DEFAULT '',
  visibility TEXT DEFAULT 'public',
  passcode_hash TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Semesters Table
CREATE TABLE IF NOT EXISTS public.semesters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id TEXT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  semester_name TEXT NOT NULL,
  semester_order INT DEFAULT 1
);

-- 3. Subjects Table
CREATE TABLE IF NOT EXISTS public.subjects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  semester_id BIGINT NOT NULL REFERENCES public.semesters(id) ON DELETE CASCADE,
  subject_code TEXT DEFAULT '',
  subject_name TEXT NOT NULL,
  credit NUMERIC NOT NULL
);

-- 4. Grading Scales Table
CREATE TABLE IF NOT EXISTS public.grading_scales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id TEXT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  grade TEXT NOT NULL,
  grade_point NUMERIC NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.semesters ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.grading_scales ENABLE ROW LEVEL SECURITY;

-- Public RLS Policies for Profiles
DROP POLICY IF EXISTS "Public profiles read access" ON public.profiles;
CREATE POLICY "Public profiles read access" ON public.profiles FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public profiles insert access" ON public.profiles;
CREATE POLICY "Public profiles insert access" ON public.profiles FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Public profiles update access" ON public.profiles;
CREATE POLICY "Public profiles update access" ON public.profiles FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Public profiles delete access" ON public.profiles;
CREATE POLICY "Public profiles delete access" ON public.profiles FOR DELETE USING (true);

-- Public RLS Policies for Semesters
DROP POLICY IF EXISTS "Public semesters read access" ON public.semesters;
CREATE POLICY "Public semesters read access" ON public.semesters FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public semesters insert access" ON public.semesters;
CREATE POLICY "Public semesters insert access" ON public.semesters FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Public semesters update access" ON public.semesters;
CREATE POLICY "Public semesters update access" ON public.semesters FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Public semesters delete access" ON public.semesters;
CREATE POLICY "Public semesters delete access" ON public.semesters FOR DELETE USING (true);

-- Public RLS Policies for Subjects
DROP POLICY IF EXISTS "Public subjects read access" ON public.subjects;
CREATE POLICY "Public subjects read access" ON public.subjects FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public subjects insert access" ON public.subjects;
CREATE POLICY "Public subjects insert access" ON public.subjects FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Public subjects update access" ON public.subjects;
CREATE POLICY "Public subjects update access" ON public.subjects FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Public subjects delete access" ON public.subjects;
CREATE POLICY "Public subjects delete access" ON public.subjects FOR DELETE USING (true);

-- Public RLS Policies for Grading Scales
DROP POLICY IF EXISTS "Public grading scales read access" ON public.grading_scales;
CREATE POLICY "Public grading scales read access" ON public.grading_scales FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public grading scales insert access" ON public.grading_scales;
CREATE POLICY "Public grading scales insert access" ON public.grading_scales FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Public grading scales update access" ON public.grading_scales;
CREATE POLICY "Public grading scales update access" ON public.grading_scales FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Public grading scales delete access" ON public.grading_scales;
CREATE POLICY "Public grading scales delete access" ON public.grading_scales FOR DELETE USING (true);
