-- =============================================================
-- CALCULATE GPA PLUS - SUPABASE FREE DATABASE SCHEMA SCRIPT
-- Paste this script into your Supabase SQL Editor and click "Run"
-- =============================================================

-- Safe Migration for existing Supabase projects
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS profile_id TEXT DEFAULT '';
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS department TEXT DEFAULT '';
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS password_hash TEXT DEFAULT '';
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS passcode_hash TEXT DEFAULT '';
ALTER TABLE public.subjects ADD COLUMN IF NOT EXISTS module_number TEXT DEFAULT '';

-- 1. Profiles Table
CREATE TABLE IF NOT EXISTS public.profiles (
  id TEXT PRIMARY KEY,
  profile_id TEXT DEFAULT '',
  profile_name TEXT NOT NULL,
  university TEXT NOT NULL,
  faculty TEXT NOT NULL,
  department TEXT DEFAULT '',
  degree TEXT DEFAULT '',
  academic_year TEXT DEFAULT '',
  description TEXT DEFAULT '',
  visibility TEXT DEFAULT 'public',
  password_hash TEXT DEFAULT '',
  passcode_hash TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for ultra-fast filtering & searching
CREATE INDEX IF NOT EXISTS idx_profiles_id ON public.profiles(id);
CREATE INDEX IF NOT EXISTS idx_profiles_name ON public.profiles(profile_name);
CREATE INDEX IF NOT EXISTS idx_profiles_university ON public.profiles(university);
CREATE INDEX IF NOT EXISTS idx_profiles_faculty ON public.profiles(faculty);
CREATE INDEX IF NOT EXISTS idx_profiles_department ON public.profiles(department);
CREATE INDEX IF NOT EXISTS idx_profiles_academic_year ON public.profiles(academic_year);
CREATE INDEX IF NOT EXISTS idx_profiles_visibility ON public.profiles(visibility);

-- 2. Semesters Table
CREATE TABLE IF NOT EXISTS public.semesters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id TEXT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  semester_name TEXT NOT NULL,
  semester_order INT DEFAULT 1
);

CREATE INDEX IF NOT EXISTS idx_semesters_profile_id ON public.semesters(profile_id);

-- 3. Subjects Table
CREATE TABLE IF NOT EXISTS public.subjects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  semester_id BIGINT NOT NULL REFERENCES public.semesters(id) ON DELETE CASCADE,
  subject_code TEXT DEFAULT '',
  module_number TEXT DEFAULT '',
  subject_name TEXT NOT NULL,
  credit NUMERIC NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_subjects_semester_id ON public.subjects(semester_id);
CREATE INDEX IF NOT EXISTS idx_subjects_subject_code ON public.subjects(subject_code);

-- 4. Grading Scales Table
CREATE TABLE IF NOT EXISTS public.grading_scales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id TEXT NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  grade TEXT NOT NULL,
  grade_point NUMERIC NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_grading_scales_profile_id ON public.grading_scales(profile_id);

-- Enable Row Level Security (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.semesters ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.grading_scales ENABLE ROW LEVEL SECURITY;

-- Public RLS Policies for Profiles (Read access enabled for shared public profiles)
DROP POLICY IF EXISTS "Public profiles read access" ON public.profiles;
CREATE POLICY "Public profiles read access" ON public.profiles FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public profiles insert access" ON public.profiles;
CREATE POLICY "Public profiles insert access" ON public.profiles FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Public profiles update access" ON public.profiles;
CREATE POLICY "Public profiles update access" ON public.profiles FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Public profiles delete access" ON public.profiles;
CREATE POLICY "Public profiles delete access" ON public.profiles FOR DELETE USING (true);

-- Public RLS Policies for Semesters
DROP POLICY IF EXISTS "Public semesters read access" ON public.semesters;
CREATE POLICY "Public semesters read access" ON public.semesters FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public semesters insert access" ON public.semesters;
CREATE POLICY "Public semesters insert access" ON public.semesters FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Public semesters update access" ON public.semesters;
CREATE POLICY "Public semesters update access" ON public.semesters FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Public semesters delete access" ON public.semesters;
CREATE POLICY "Public semesters delete access" ON public.semesters FOR DELETE USING (true);

-- Public RLS Policies for Subjects
DROP POLICY IF EXISTS "Public subjects read access" ON public.subjects;
CREATE POLICY "Public subjects read access" ON public.subjects FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public subjects insert access" ON public.subjects;
CREATE POLICY "Public subjects insert access" ON public.subjects FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Public subjects update access" ON public.subjects;
CREATE POLICY "Public subjects update access" ON public.subjects FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Public subjects delete access" ON public.subjects;
CREATE POLICY "Public subjects delete access" ON public.subjects FOR DELETE USING (true);

-- Public RLS Policies for Grading Scales
DROP POLICY IF EXISTS "Public grading scales read access" ON public.grading_scales;
CREATE POLICY "Public grading scales read access" ON public.grading_scales FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public grading scales insert access" ON public.grading_scales;
CREATE POLICY "Public grading scales insert access" ON public.grading_scales FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Public grading scales update access" ON public.grading_scales;
CREATE POLICY "Public grading scales update access" ON public.grading_scales FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Public grading scales delete access" ON public.grading_scales;
CREATE POLICY "Public grading scales delete access" ON public.grading_scales FOR DELETE USING (true);
